# Generated by Django 3.1.6 on 2021-04-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210413_0634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='liked_categories',
            new_name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=240, null=True, verbose_name='Location'),
        ),
    ]
