# Generated by Django 3.1.6 on 2021-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210427_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='World', max_length=240, verbose_name='Location'),
        ),
    ]
