# Generated by Django 3.1.6 on 2021-04-28 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210428_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
