# Generated by Django 3.1.6 on 2021-04-28 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0016_auto_20210425_1003'),
        ('accounts', '0008_delete_userfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='interests', to='images.Collection'),
        ),
    ]
