version: "3.8"

services:
  backend:
    container_name: backend
    expose:
      - 8000
    env_file:
      - ./app/.env.prod
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    build:
      context: .
      dockerfile: backend.prod.dockerfile
    volumes:
      - static_files:/app/staticfiles/
      - media_files:/app/mediafiles/

  nginx:
    container_name: nginx
    restart: always
    depends_on: 
      - backend
    build: 
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - 1337:80
    volumes:
      - static_files:/app/staticfiles/
      - media_files:/app/mediafiles/

volumes:
  static_files:
  media_files: