version: '3.8'

services:
  # NOTE: no db volume as want db to reset on container restart
  db:
    container_name: db
    build:
      context: .
      dockerfile: postgres.dockerfile
    ports:
      - '5432:5432'

  # caching, websockets
  redis:
    image: redis:6.2.1-alpine
    container_name: redis
    ports:
      - '6379:6379'

  # main application
  backend:
    container_name: backend
    build:
      context: ../
      dockerfile: dev/backend.dev.dockerfile
      args:
        INSTALL_DEV: 'true'
    ports:
      - '8000:8000'
    volumes:
      - ../:/usr/src/
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
      - redis
    command: python manage.py runserver 0.0.0.0:8000
