# Generated by Django 3.1.6 on 2021-02-03 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_text', models.TextField(editable=False, verbose_name='Generated Caption')),
                ('satisfactory', models.BooleanField(null=True, verbose_name='Satisfactory')),
                ('corrected_text', models.TextField(blank=True, verbose_name='Corrected Caption')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True, verbose_name='Category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Userx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=240, verbose_name='Full name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('filename', models.CharField(max_length=240, verbose_name='Filename')),
                ('title', models.CharField(db_index=True, max_length=240, verbose_name='Title')),
                ('uuid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_profile_image', models.BooleanField(default=False)),
                ('caption', models.ForeignKey(blank=True, on_delete=models.SET(''), to='images.caption')),
                ('collections', models.ManyToManyField(related_name='images', to='images.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.userx')),
            ],
            options={
                'ordering': ['uploaded_at', 'title'],
            },
        ),
    ]
