# Generated by Django 3.1.6 on 2021-02-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='satisfactory',
            field=models.BooleanField(default=True, null=True, verbose_name='Satisfactory'),
        ),
    ]
