# Generated by Django 3.1.6 on 2021-02-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210204_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='corrected_text',
            field=models.CharField(blank=True, db_index=True, max_length=240, verbose_name='Corrected Caption'),
        ),
        migrations.AlterField(
            model_name='caption',
            name='text',
            field=models.CharField(db_index=True, max_length=240, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='category',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Category'),
        ),
    ]
