# Generated by Django 3.1.6 on 2021-02-15 11:56

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_collection_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(storage=storages.backends.s3boto3.S3Boto3Storage(bucket_name='image-captioning-images'), upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(blank=True, db_index=True, max_length=240, verbose_name='Title'),
        ),
    ]
