version: '3.8'

services:
  # main application
  backend:
    container_name: backend
    image: 396432430368.dkr.ecr.ap-southeast-2.amazonaws.com/captionai:backend
    restart: always
    build:
      context: ../
      dockerfile: prod/backend.dockerfile
    env_file:
      - .env
    ports:
      - '8000:8000'
    depends_on:
      - redis
    command: daphne -b 0.0.0.0 -p 8000 app.asgi:application

  # caching, websockets
  redis:
    image: redis:6.2.1-alpine
    container_name: redis
    ports:
      - '6379:6379'

  # reverse proxy
  nginx:
    container_name: nginx
    image: nginx:1.20-alpine
    restart: always
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

  # # https
  certbot:
    container_name: certbot
    image: certbot/dns-route53
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
