# Generated by Django 3.1.6 on 2021-02-18 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Category')),
                ('description', models.CharField(blank=True, max_length=240, verbose_name='Description')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('title', models.CharField(blank=True, db_index=True, max_length=240, verbose_name='Title')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_profile_image', models.BooleanField(default=False, verbose_name='Profile image')),
                ('collections', models.ManyToManyField(related_name='images', to='images.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=240, verbose_name='Caption')),
                ('satisfactory', models.BooleanField(default=True, null=True, verbose_name='Satisfactory')),
                ('corrected_text', models.CharField(blank=True, db_index=True, max_length=240, verbose_name='Corrected Caption')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='images.image')),
            ],
        ),
    ]
