# Generated by Django 3.1.6 on 2021-03-18 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Category')),
                ('is_main', models.BooleanField(default=False, verbose_name='Main category')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
                ('title', models.CharField(blank=True, db_index=True, max_length=240, verbose_name='Title')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_profile_image', models.BooleanField(default=False, verbose_name='Profile image')),
                ('is_private', models.BooleanField(default=False, verbose_name='Private image')),
                ('collections', models.ManyToManyField(blank=True, default='Uncategorised', related_name='images', to='images.Collection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Caption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(db_index=True, max_length=240, verbose_name='Caption')),
                ('satisfactory', models.BooleanField(default=True, verbose_name='Satisfactory')),
                ('corrected_text', models.CharField(blank=True, db_index=True, max_length=240, verbose_name='Corrected Caption')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caption', to='images.image')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Bio')),
                ('liked_categories', models.ManyToManyField(blank=True, related_name='profile', to='images.Collection')),
                ('liked_images', models.ManyToManyField(blank=True, related_name='profile', to='images.Image')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='Likes')),
                ('dislikes', models.PositiveIntegerField(default=0, verbose_name='Dislikes')),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='images.image')),
            ],
            options={
                'ordering': ['-commented_at'],
            },
        ),
    ]
