# Generated by Django 3.1.6 on 2021-02-26 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='description',
        ),
        migrations.AddField(
            model_name='caption',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collection',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Main category'),
        ),
        migrations.AddField(
            model_name='image',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='collections',
            field=models.ManyToManyField(default='Uncategorised', related_name='images', to='images.Collection'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image'),
        ),
    ]
