# Generated by Django 3.1.6 on 2021-03-18 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='user',
            new_name='uploader',
        ),
        migrations.AddField(
            model_name='image',
            name='dislikes',
            field=models.PositiveIntegerField(default=0, verbose_name='Dislikes'),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Likes'),
        ),
    ]
