# Generated by Django 3.1.6 on 2021-03-15 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210226_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='image',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caption', to='images.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('af457e3d-400e-416f-9518-b4fa7bf7716d'), editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
