# Generated by Django 3.1.6 on 2021-02-25 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_auto_20210221_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='is_private',
            field=models.BooleanField(default=False, verbose_name='Private image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='collections',
            field=models.ManyToManyField(default='Uncategorised', related_name='images', to='images.Collection'),
        ),
    ]
