# Generated by Django 3.1.6 on 2021-03-18 17:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_auto_20210318_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_comments',
            field=models.ManyToManyField(blank=True, related_name='profile_dislikes', to='images.Comment'),
        ),
        migrations.AddField(
            model_name='profile',
            name='disliked_images',
            field=models.ManyToManyField(blank=True, related_name='profile_dislikes', to='images.Image'),
        ),
        migrations.AddField(
            model_name='profile',
            name='liked_comments',
            field=models.ManyToManyField(blank=True, related_name='profile_likes', to='images.Comment'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_categories',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='images.Collection'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_images',
            field=models.ManyToManyField(blank=True, related_name='profile_likes', to='images.Image'),
        ),
    ]
