# Generated by Django 3.1.6 on 2021-03-17 05:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210315_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='collections',
            field=models.ManyToManyField(blank=True, default='Uncategorised', related_name='images', to='images.Collection'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
