# Generated by Django 3.1.6 on 2021-03-22 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210318_2029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
