# Generated by Django 3.1.6 on 2021-03-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Image', width_field='width'),
        ),
    ]
