# Generated by Django 3.1.6 on 2021-04-02 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20210330_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='s3_key',
            field=models.CharField(default='CHANGE', max_length=240, verbose_name='Key'),
            preserve_default=False,
        ),
    ]
