# Generated by Django 3.1.6 on 2021-04-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20210402_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(db_index=True, max_length=240, verbose_name='Title'),
        ),
    ]
