# Generated by Django 3.1.6 on 2021-04-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_auto_20210402_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='satisfactory',
            field=models.BooleanField(null=True, verbose_name='Satisfactory'),
        ),
    ]
