# Generated by Django 3.1.6 on 2021-04-11 14:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_auto_20210409_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caption',
            name='text',
            field=models.CharField(db_index=True, max_length=500, verbose_name='Caption'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='UUID'),
        ),
    ]
