# Generated by Django 3.1.6 on 2021-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0014_auto_20210411_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='caption',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_edited',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='downloads',
            field=models.PositiveIntegerField(default=0, verbose_name='Downloads'),
        ),
        migrations.AddField(
            model_name='image',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='Views'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='image',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='images', to='images.Collection'),
        ),
        migrations.AlterField(
            model_name='image',
            name='uploader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaders', to=settings.AUTH_USER_MODEL),
        ),
    ]
