# Generated by Django 3.1.6 on 2021-04-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_auto_20210418_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='type',
            field=models.CharField(default='JPG', max_length=100, verbose_name='Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='height',
            field=models.PositiveIntegerField(default=0, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='image',
            name='width',
            field=models.PositiveIntegerField(default=0, verbose_name='Width'),
        ),
    ]
