# Generated by Django 3.1.6 on 2021-04-18 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0015_auto_20210418_1124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=500, verbose_name='Comments')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('solved', models.BooleanField(default=False, verbose_name='Solved')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('solved_at', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('LEGAL', 'Infringes my rights'), ('VIOLENT', 'Violent or repulsive'), ('HATEFUL', 'Hateful or abusive'), ('SEXUAL', 'Sexually explicit material'), ('SPAM', 'Spam or misleading'), ('CAPTION', 'Caption issue'), ('HARASSMENT', 'Bullying or harassment'), ('OTHER', 'Other')], max_length=20)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='images.image')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_reviewers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_reporters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Image',
            },
        ),
        migrations.CreateModel(
            name='CommentReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField(blank=True, max_length=500, verbose_name='Comments')),
                ('reviewed', models.BooleanField(default=False, verbose_name='Reviewed')),
                ('solved', models.BooleanField(default=False, verbose_name='Solved')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(null=True)),
                ('solved_at', models.DateTimeField(null=True)),
                ('type', models.CharField(choices=[('VIOLENT', 'Violent or repulsive'), ('HATEFUL', 'Hateful or abusive'), ('SEXUAL', 'Sexually explicit material'), ('SPAM', 'Spam or misleading'), ('HARASSMENT', 'Bullying or harassment'), ('OTHER', 'Other')], max_length=20)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='images.comment')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_reviewers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reporters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comment',
            },
        ),
    ]
